name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore AspNetCore.Scheduler.Quartz/AspNetCore.Scheduler.Quartz.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore AspNetCore.Scheduler.Quartz/AspNetCore.Scheduler.Quartz.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal AspNetCore.Scheduler.Quartz/AspNetCore.Scheduler.Quartz.csproj
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: AspNetCore.Scheduler.Quartz/AspNetCore.Scheduler.Quartz.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
