name: Connection.Identifier.Quoting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./Connection.Identifier.Quoting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore Connection.Identifier.Quoting/Connection.Identifier.Quoting.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore Connection.Identifier.Quoting/Connection.Identifier.Quoting.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal Connection.Identifier.Quoting/Connection.Identifier.Quoting.csproj
      - name: Publish
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: Connection.Identifier.Quoting/Connection.Identifier.Quoting.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
