name: Service.Scheduler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./Service.Scheduler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore Service.Scheduler/Service.Scheduler.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore Service.Scheduler/Service.Scheduler.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal Service.Scheduler/Service.Scheduler.csproj
      - name: Publish
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: Service.Scheduler/Service.Scheduler.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
